import "./globals.css";
import { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const openSana = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={openSana.className} lang='en'>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
